/*
 Copyright (C) 2013 United States Government as represented by the Administrator of the
 National Aeronautics and Space Administration. All Rights Reserved.
 
 @version $Id$
 */

#import <Foundation/Foundation.h>

@class WWGlobe;
@class WWVec4;

/**
* Provides an interface to terrain queries and operations. Terrain is generated by a tessellator using one or more
* elevation models.
*/
@protocol WWTerrain

/// @name Terrain Attributes

/**
* Indicates the globe associated with this terrain.
*
* @return The globe associated with this terrain.
*/
- (WWGlobe*) globe;

/**
* Indicates the vertical exaggeration associated with this terrain.
*
* @return The vertical exaggeration associated with this terrain.
*/
- (double) verticalExaggeration;

/// @name Computing Points On or Relative to Terrain

/**
* Computes a point on the terrain at a specified location and applies an optional offset from the terrain.
*
* @param latitude The point's latitude.
* @param longitude The point's longitude.
* @param offset A distance in meters to offset the point from the terrain surface.
* @param result The location in which to return the computed point.
*
* @exception NSInvalidArgumentException If the specified result is nil.
*/
- (void) surfacePointAtLatitude:(double)latitude
                      longitude:(double)longitude
                         offset:(double)offset
                         result:(WWVec4*)result;

/**
* Computes a point on or relative to the terrain at a specified location and applies an optional offset from the
* terrain.
*
* This method applies a specified altitude mode to determine how the computed point relates to the terrain. Valid
* values are WW_ALTITUDE_MODE_CLAMP_TO_GROUND, WW_ALTITUDE_MODE_RELATIVE_TO_GROUND and WW_ALTITUDE_MODE_ABSOLUTE.
*
* @param latitude The point's latitude.
* @param longitude The point's longitude.
* @param offset A distance in meters to offset the point from the terrain surface.
* @param altitudeMode The altitude mode to apply when computing the point.
* @param result The location in which to return the computed point.
*
* @exception NSInvalidArgumentException If the specified result is nil.
*/
- (void) surfacePointAtLatitude:(double)latitude
                      longitude:(double)longitude
                         offset:(double)offset
                   altitudeMode:(NSString*)altitudeMode
                         result:(WWVec4*)result;

@end