/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "AppIcon": { "view": "DC.ImageLayout" },
    "AppTitle": { "text": "World Wind Examples", "view": "DC.Text" },
    "footer": { "text": "Copyright (C) 2013 United States Government", "view": "DC.Text" },
    "text": { "text": "Install the World Wind Examples app by browsing to http://worldwindserver.net/ios/examples using Safari on your iPad.", "view": "DC.Text" }
};





